"""file_audit / probes の結果から Markdown レポート (SECURITY.md 形式) を組み立てる。"""
from __future__ import annotations

import datetime

from .probes.runner import ProbeReport


def build_file_audit_section(audit_result: dict) -> str:
    checksums_text = "\n".join(f"{v}  {k}" for k, v in audit_result["checksums"].items())
    risky = audit_result["risky_pickle_files"]
    code_files = audit_result["custom_code_files"]

    if risky:
        risky_text = (
            f"⚠️ pickle形式のファイルが検出されました: {', '.join(risky)}\n"
            "任意コード実行のリスクがあります。内容を確認するか、safetensors形式への変換を検討してください。"
        )
    else:
        risky_text = "pickle形式（`.bin`/`.pt`/`.pth`/`.pkl`など）は検出されませんでした。"

    if code_files:
        files_list = "、".join(f"`{f}`" for f in code_files)
        code_text = (
            f"このリポジトリには独自のPythonコード（{files_list}）が同梱されています。"
            "モデルを利用する前に内容をご確認ください。"
        )
    else:
        code_text = "`trust_remote_code`が必要なカスタムPythonコードは検出されませんでした。"

    return f"""## 配布物としての安全性監査

- **pickle形式チェック**: {risky_text}
- **同梱コードチェック**: {code_text}
- **チェックサム (SHA256)**:

```
{checksums_text}
```
"""


CATEGORY_LABELS_JA = {
    "instruction-override": "指示上書き",
    "roleplay-jailbreak": "ロールプレイ脱獄",
    "harmful-code-generation": "有害コード生成",
    "data-leak-elicitation": "データ漏洩誘導",
    "prompt-injection-in-content": "プロンプトインジェクション（コンテンツ内埋め込み）",
    "privilege-escalation": "権限昇格・社会工学",
    "illegal-activity-instructions": "違法行為の指南",
    "system-prompt-extraction": "システムプロンプト抽出",
}


def build_probe_section(report: ProbeReport, lang: str = "ja") -> str:
    rows = []
    for r in report.results:
        label = CATEGORY_LABELS_JA.get(r.category, r.category) if lang == "ja" else r.category
        mark = "✅" if r.heuristic_safe else "❌"
        rows.append(f"| {r.id} | {label} | {mark} |")
    rows_text = "\n".join(rows)

    return f"""## 簡易安全性テスト（プロンプトインジェクション/データ漏洩）

既知の代表的な攻撃パターン{report.total}件による簡易テストの結果です。

| ID | カテゴリ | ヒューリスティック判定 |
|---|---|---|
{rows_text}

**{report.total}件中{report.safe_count}件が安全側の挙動でした。**

### 重要な注意事項（必ずお読みください）

- これは**限定的な既知パターンによる簡易チェック**であり、包括的なセキュリティ監査ではありません。
- 「ヒューリスティック判定」は拒否フレーズの有無などの単純な文字列マッチによる**一次スクリーニング**です。
  最終判断は必ず`response`本文を人間が読んで行ってください（false positive/negativeがあり得ます）。
- 成功した項目も、**未知の攻撃手法への耐性を保証するものではありません**。
- 本番環境でモデルを使う場合は、モデル単体の挙動に頼らず、アプリケーション側でも入力サニタイズや
  出力フィルタリングなどの独自のガードレールを実装することを推奨します。
"""


def write_security_md(
    audit_result: dict | None = None,
    probe_report: ProbeReport | None = None,
    repo_id: str | None = None,
) -> str:
    date = datetime.date.today().isoformat()
    title_repo = repo_id or (audit_result or {}).get("repo_id", "")
    parts = [f"# セキュリティー監査情報: {title_repo}\n\n{date}時点でのmodel-audit-liteによる自動監査結果です。\n"]
    if audit_result is not None:
        parts.append(build_file_audit_section(audit_result))
    if probe_report is not None:
        parts.append(build_probe_section(probe_report))
    parts.append(
        "---\n\nGenerated by [model-audit-lite](https://github.com/masahirocom/model-audit-lite)."
    )
    return "\n".join(parts)
