"""file_audit / probes の結果から Markdown レポートを組み立てる（日英対応）。"""
from __future__ import annotations

import datetime

from .probes.runner import ProbeReport

CATEGORY_LABELS_JA = {
    "instruction-override": "指示上書き",
    "roleplay-jailbreak": "ロールプレイ脱獄",
    "harmful-code-generation": "有害コード生成",
    "data-leak-elicitation": "データ漏洩誘導",
    "prompt-injection-in-content": "プロンプトインジェクション（コンテンツ内埋め込み）",
    "privilege-escalation": "権限昇格・社会工学",
    "illegal-activity-instructions": "違法行為の指南",
    "system-prompt-extraction": "システムプロンプト抽出",
}

_STRINGS = {
    "ja": {
        "title": "セキュリティー監査情報",
        "generated_by_date": "{date}時点でのmodel-audit-liteによる自動監査結果です。",
        "file_audit_heading": "## 配布物としての安全性監査",
        "pickle_check_label": "**pickle形式チェック**",
        "pickle_found": (
            "⚠️ pickle形式のファイルが検出されました: {files}\n"
            "  任意コード実行のリスクがあります。内容を確認するか、safetensors形式への変換を検討してください。"
        ),
        "pickle_clean": "pickle形式（`.bin`/`.pt`/`.pth`/`.pkl`など）は検出されませんでした。",
        "code_check_label": "**同梱コードチェック**",
        "code_found": "このリポジトリには独自のPythonコード（{files}）が同梱されています。モデルを利用する前に内容をご確認ください。",
        "code_clean": "`trust_remote_code`が必要なカスタムPythonコードは検出されませんでした。",
        "checksums_label": "**チェックサム (SHA256)**",
        "probe_heading": "## 簡易安全性テスト（プロンプトインジェクション/データ漏洩）",
        "probe_intro": "既知の代表的な攻撃パターン{n}件による簡易テストの結果です。",
        "table_header": "| ID | カテゴリ | ヒューリスティック判定 |\n|---|---|---|",
        "summary": "**{n}件中{safe}件が安全側の挙動でした。**",
        "notes_heading": "### 重要な注意事項（必ずお読みください）",
        "notes": [
            "これは**限定的な既知パターンによる簡易チェック**であり、包括的なセキュリティ監査ではありません。",
            "「ヒューリスティック判定」は拒否フレーズの有無などの単純な文字列マッチによる**一次スクリーニング**です。"
            "最終判断は必ず`response`本文を人間が読んで行ってください（false positive/negativeがあり得ます）。",
            "成功した項目も、**未知の攻撃手法への耐性を保証するものではありません**。",
            "本番環境でモデルを使う場合は、モデル単体の挙動に頼らず、アプリケーション側でも入力サニタイズや"
            "出力フィルタリングなどの独自のガードレールを実装することを推奨します。",
        ],
        "footer": "Generated by [model-audit-lite](https://github.com/masahirocom/model-audit-lite).",
    },
    "en": {
        "title": "Security Audit Report",
        "generated_by_date": "Automated audit generated by model-audit-lite on {date}.",
        "file_audit_heading": "## File-Distribution Safety Audit",
        "pickle_check_label": "**Pickle-format check**",
        "pickle_found": (
            "⚠️ Pickle-format file(s) detected: {files}\n"
            "  These carry an arbitrary-code-execution risk. Review the contents or convert to safetensors."
        ),
        "pickle_clean": "No pickle-format files (`.bin`/`.pt`/`.pth`/`.pkl`, etc.) detected.",
        "code_check_label": "**Bundled custom-code check**",
        "code_found": "This repository bundles custom Python code ({files}). Please review it before using the model.",
        "code_clean": "No custom Python code requiring `trust_remote_code` was detected.",
        "checksums_label": "**Checksums (SHA256)**",
        "probe_heading": "## Lightweight Safety Probe (prompt injection / data leakage)",
        "probe_intro": "Results of a lightweight test using {n} known attack patterns.",
        "table_header": "| ID | Category | Heuristic verdict |\n|---|---|---|",
        "summary": "**{safe}/{n} probes showed the expected safe behavior.**",
        "notes_heading": "### Important notes (please read)",
        "notes": [
            "This is a **lightweight check against a limited set of known patterns**, not a comprehensive security audit.",
            "The heuristic verdict is a **first-pass string-match screen** (refusal-phrase detection, etc.), not a judgment. "
            "Always read the raw `response` text yourself before trusting a result (false positives/negatives are possible).",
            "A passing result does **not** guarantee robustness against unknown attack techniques.",
            "In production, don't rely on model behavior alone -- implement your own guardrails "
            "(input sanitization, output filtering) at the application layer as well.",
        ],
        "footer": "Generated by [model-audit-lite](https://github.com/masahirocom/model-audit-lite).",
    },
}


def build_file_audit_section(audit_result: dict, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    checksums_text = "\n".join(f"{v}  {k}" for k, v in audit_result["checksums"].items())
    risky = audit_result["risky_pickle_files"]
    code_files = audit_result["custom_code_files"]

    pickle_text = s["pickle_found"].format(files=", ".join(risky)) if risky else s["pickle_clean"]
    code_text = (
        s["code_found"].format(files="、".join(f"`{f}`" for f in code_files) if lang == "ja" else ", ".join(f"`{f}`" for f in code_files))
        if code_files
        else s["code_clean"]
    )

    return f"""{s['file_audit_heading']}

- {s['pickle_check_label']}: {pickle_text}
- {s['code_check_label']}: {code_text}
- {s['checksums_label']}:

```
{checksums_text}
```
"""


def build_probe_section(report: ProbeReport, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    rows = []
    for r in report.results:
        label = CATEGORY_LABELS_JA.get(r.category, r.category) if lang == "ja" else r.category
        mark = "✅" if r.heuristic_safe else "❌"
        rows.append(f"| {r.id} | {label} | {mark} |")
    rows_text = "\n".join(rows)
    notes_text = "\n".join(f"- {n}" for n in s["notes"])

    return f"""{s['probe_heading']}

{s['probe_intro'].format(n=report.total)}

{s['table_header']}
{rows_text}

{s['summary'].format(n=report.total, safe=report.safe_count)}

{s['notes_heading']}

{notes_text}
"""


def write_security_md(
    audit_result: dict | None = None,
    probe_report: ProbeReport | None = None,
    repo_id: str | None = None,
    lang: str = "ja",
) -> str:
    s = _STRINGS[lang]
    date = datetime.date.today().isoformat()
    title_repo = repo_id or (audit_result or {}).get("repo_id", "")
    parts = [f"# {s['title']}: {title_repo}\n\n{s['generated_by_date'].format(date=date)}\n"]
    if audit_result is not None:
        parts.append(build_file_audit_section(audit_result, lang=lang))
    if probe_report is not None:
        parts.append(build_probe_section(probe_report, lang=lang))
    parts.append(f"---\n\n{s['footer']}")
    return "\n".join(parts)
